In [363]:
import pandas 
import matplotlib
import seaborn

import pandas as pd
#df = pd.read_csv("vehicles_dataset.csv")

In [364]:
pd.set_option('display.max_columns', None)

#Read Car List dataframe and show maximum columns
 
df_CarList = pd.read_csv("vehicles_dataset.csv")
df_CarList.info(max_cols=20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 906 entries, 0 to 905
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          906 non-null    object
 1   make          906 non-null    object
 2   model         906 non-null    object
 3   year          906 non-null    int64
 4   price         904 non-null    float64
 5   cylinders     906 non-null    object
 6   transmission  906 non-null    object
 7   trim          906 non-null    object
 8   body          906 non-null    object
 9   drivetrain    906 non-null    object
dtypes: float64(1), int64(1), object(8)
memory usage: 70.9+ KB

In [365]:
df_CarList = df_CarList[df_CarList['year'] == 2024]
df.reset_index(drop=True, inplace=True)

Find Missing values

In [366]:

df_CarList[df_CarList.isnull().any(axis=1)]

,name,make,model,year,price,cylinders,transmission,trim,body,drivetrain
614,2024 Mercedes-Benz GLE 350 Base 4MATIC,Mercedes-Benz,GLE 350,2024,NaN,4.0,9-Speed Automatic,Base 4MATIC,SUV,All-wheel Drive
728,2024 BMW 530 i,BMW,530,2024,NaN,4.0,8-Speed Automatic,i,Sedan,Rear-wheel Drive

<font size="4">We have 252 rows of missing values. Lets clean this up by removing uneccessary columns and remove rows with NaN values

In [367]:

#df_CarList.to_csv('vehicles_dataset.csv', index=False) #Saves cleaned data to a new file

In [368]:
#df_CarList.drop(columns=["description","fuel","type","engine","interior_color","exterior_color","mileage","doors"], inplace=True)

In [369]:
df_CarList.drop_duplicates()

,name,make,model,year,price,cylinders,transmission,trim,body,drivetrain
0,2024 Jeep Wagoneer Series II,Jeep,Wagoneer,2024,74600.0,6.0,8-Speed Automatic,Series II,SUV,Four-wheel Drive
1,2024 Jeep Grand Cherokee Laredo,Jeep,Grand Cherokee,2024,50170.0,6.0,8-Speed Automatic,Laredo,SUV,Four-wheel Drive
2,2024 GMC Yukon XL Denali,GMC,Yukon XL,2024,96410.0,8.0,Automatic,Denali,SUV,Four-wheel Drive
3,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive
4,2024 Nissan Murano Platinum,Nissan,Murano,2024,46000.0,6.0,Automatic CVT,Platinum,SUV,All-wheel Drive
...,...,...,...,...,...,...,...,...,...,...
900,2024 RAM 2500 Tradesman,RAM,2500,2024,69315.0,6.0,Automatic,Tradesman,Pickup Truck,Four-wheel Drive
901,2024 Mercedes-Benz Sprinter 2500 Standard Roof,Mercedes-Benz,Sprinter 2500,2024,59037.0,4.0,9-Speed Automatic,Standard Roof,Cargo Van,Rear-wheel Drive
903,2024 Jeep Wagoneer Base,Jeep,Wagoneer,2024,69085.0,6.0,8-Speed Automatic,Base,SUV,Four-wheel Drive
904,2024 Nissan Murano SV Intelligent AWD,Nissan,Murano,2024,43495.0,6.0,Automatic,SV Intelligent AWD,SUV,All-wheel Drive
905,2024 Chevrolet Silverado 2500 WT,Chevrolet,Silverado 2500,2024,48995.0,8.0,Automatic,WT,Pickup Truck,Rear-wheel Drive

In [381]:
#df.isnull().sum()
df_CarList.isnull().sum()

name            0
make            0
model           0
year            0
price           0
cylinders       0
transmission    0
trim            0
body            0
drivetrain      0
dtype: int64

In [371]:
#Find missing values again which resulted in 130 this time
df_CarList[df_CarList.isnull().any(axis=1)]

,name,make,model,year,price,cylinders,transmission,trim,body,drivetrain
614,2024 Mercedes-Benz GLE 350 Base 4MATIC,Mercedes-Benz,GLE 350,2024,NaN,4.0,9-Speed Automatic,Base 4MATIC,SUV,All-wheel Drive
728,2024 BMW 530 i,BMW,530,2024,NaN,4.0,8-Speed Automatic,i,Sedan,Rear-wheel Drive

In [372]:
#Replacing NaN vaules in cyclinder with 'Eletric' for the Electric Vehicles
df_CarList['cylinders']= df_CarList['cylinders'].fillna("Electric")

#Filling missing values in transmiddion column
df_CarList['transmission']=df_CarList['transmission'].fillna("Automatic")

#Adding SUV to NaNs in the column 'body'
df_CarList['body']=df_CarList['body'].fillna("SUV")

#Recheck missing values
df_CarList[df_CarList.isnull().any(axis=1)]

,name,make,model,year,price,cylinders,transmission,trim,body,drivetrain
614,2024 Mercedes-Benz GLE 350 Base 4MATIC,Mercedes-Benz,GLE 350,2024,NaN,4.0,9-Speed Automatic,Base 4MATIC,SUV,All-wheel Drive
728,2024 BMW 530 i,BMW,530,2024,NaN,4.0,8-Speed Automatic,i,Sedan,Rear-wheel Drive

In [373]:
#Recheck price column for missing values
df_CarList['price'] = df_CarList['price'].fillna(df.groupby('make')['price'].transform('mean'))
df_CarList[df_CarList.isnull().any(axis=1)]

Empty DataFrame
Columns: [name, make, model, year, price, cylinders, transmission, trim, body, drivetrain]
Index: []

In [374]:
df_CarList.isnull().sum()

name            0
make            0
model           0
year            0
price           0
cylinders       0
transmission    0
trim            0
body            0
drivetrain      0
dtype: int64

<font size="6">Dataset #1 Cleaned!

In [375]:
df_rcl = pd.read_csv("RCL_FROM_2020_2024.csv")

In [376]:
pd.set_option('display.max_columns', None)

#Read Car List dataframe and show maximum columns
df_rcl.info(max_cols=20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215506 entries, 0 to 215505
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   NHTSA ID       215506 non-null  object
 1   DOCUMENT NAME  215506 non-null  object
 2   MAKE           215506 non-null  object
 3   MODEL          215506 non-null  object
 4   MODEL YEAR     215506 non-null  int64
 5   SUMMARY        215505 non-null  object
dtypes: int64(1), object(5)
memory usage: 9.9+ MB

<font size="4">Grabbing data for only 2024 vehicles, and checking for missing values.

In [377]:
df_rcl = df_rcl[df_rcl["MODEL YEAR"] == 2024]
df_rcl.reset_index(drop=True, inplace=True)
df_rcl.isnull().sum()

NHTSA ID         0
DOCUMENT NAME    0
MAKE             0
MODEL            0
MODEL YEAR       0
SUMMARY          0
dtype: int64

<font size="4">Check and remove duplicate lines.

In [378]:
df_rcl.drop_duplicates()
df_rcl[df_rcl.isnull().any(axis=1)]
print(df_rcl.info)

<bound method DataFrame.info of      NHTSA ID          DOCUMENT NAME                  MAKE     MODEL  \
0      22V909  RCONL-22V909-2556.pdf                IC BUS      CESB
1      22V909  RCRIT-22V909-1126.pdf                IC BUS      CESB
2      23V065  RCONL-23V065-7947.pdf                IC BUS      CESB
3      23V065  RCRIT-23V065-4342.pdf                IC BUS      CESB
4      23V087  RCONL-23V087-5040.pdf              KENWORTH      T280
...       ...                    ...                   ...       ...
9458   24V966  RCONL-24V966-6482.pdf  STORYTELLER OVERLAND    MYSTIC
9459   24V966   RCMN-24V966-1472.pdf  STORYTELLER OVERLAND   STEALTH
9460   24V966  RCONL-24V966-6482.pdf  STORYTELLER OVERLAND   STEALTH
9461   24V968  RCONL-24V968-6389.pdf  STORYTELLER OVERLAND  GXV HILT
9462   24V968   RCMN-24V968-0243.pdf  STORYTELLER OVERLAND  GXV HILT

      MODEL YEAR                                            SUMMARY
0           2024  22527; 02/06/2023; IC Bus; CE - 2022 & 2023; R...
1           2024  22527; 02/01/2023; IC bus; CE - 2022 & 2023; R...
2           2024  23501; 04/03/2023; IC Bus; 2022 thru 2024 CE, ...
3           2024  23501; 04/03/2023; IC Bus; 2022 thru 2024 CE, ...
4           2024  Attached letter is the FINAL customer notifica...
...          ...                                                ...
9458        2024  This is our final Owner Notification Letter, t...
9459        2024  This our Dealer Final Notification. This docum...
9460        2024  This is our final Owner Notification Letter, t...
9461        2024  This is our Final 577 Customer Notification; t...
9462        2024  This is our final copy of our Dealer Notificat...

[9463 rows x 6 columns]>

<font size="4">Remove Semi Trucks. This data is for the purpose of regular non commercial drivers.

In [379]:
non_vehicles = ("MACK", "KENWORTH", "TOW KING", "MCI", "CUMMINS", "LIGHTING EMOTORS", "SPARTAN FIRE", "AGILITY FUEL SYSTEMS", "MOPAR", "RUGGED LINERS", "ALTEC", "KEYSTONE", "THOMAS BUILT BUSES",
                "CARRIER TRANSICOLD", "PITTSBURGH AUTOMOTIVE", "FREEDMAN", "KZRN", "PJ TRAILERS", "LODE KING", "NEXUS", "TIFFIN", "WINNEBAGO", "NIKOLA", "VINFAST", "HOLIDAY RAMBLER",
                "JAYCO", "HEARTLAND", "PRATT INTERNATIONAL", "CFMOTO", "XOS", "AIRSTREAM", "INDIAN", "WESTERN STAR", "CAN-AM", "MAINTAINER", "NOVA BUS", "THOR MOTOR COACH", "FREIGHTLINER",
                "PETERBILT", "UTILITY TRAILER", "ARCIMOTO", "NEW FLYER", "KIDRON", "LION", "TICO", "SUPER PRODUCTS", "HINO", "AUTOCAR", "TRIPPLE E", "TRIPLE R", "KAWASAKI", "SCHWARZE", 
                "KZRZ", "TRAIL KING", "CRUISER RV", "TEREX", "TEREX ADVANCED", "INTERNATIONAL", "IC BUS", "FCCC", "VERMEER", "FOREST RIVER BUS", "HUSQVARNA", "KTM", "ZERO", "VAN HOOL",
                "FLEETWOOD", "BRUAN AMBULANCE", "FEILD VAN", "STORYTELLER OVERLAND", "KME", "SAFARI CONDO", "FORETRAVEL", "CUMMINS POWER GENERATION", "MITSUBISHI FUSO", "POLESTAR",
                "AKRON BRASS COMPANY", "TEKONSHA", "DANA", "DOMETIC", "DANA", "LIPPERT", "CODE 3", "AC DELCO", "NAPA", "SAAB", "DRAW-TITE", "TIMPTE", "STARCRAFT BUS", "ENDERA", "MICRO BIRD",
                "BRINKLEY RV", "COACHMEN", "FOREST RIVER", "DELCO TRAILERS", "KME", "DOOSAN PORTABLE POWER", "MOTIV", "TAXA", "DOOSAN", "LIVEWIRE", "ROSENBAUER", "CRUISER", "MORBARK", 
                "KENTUCY TRAILER KY", "HARLEY-DAVIDSON", "ROYAL ENFIELD", "CATALINA", "DYNAMAX", "EAST TO WEST", "ATC", "NEWMAR", "AURORA", "VANCRAFT", "OLIVER TRAVEL TRAILERS", "PIERCE", "VIKING TRAVEL TRAILERS")

df_rcl = df_rcl[~df_rcl['MAKE'].isin(non_vehicles)]
df_rcl.reset_index(drop=True, inplace=True)

In [380]:
df_rcl[df_rcl.isnull().any(axis=1)]
print(df_rcl.info)
df_rcl.head(20)

<bound method DataFrame.info of      NHTSA ID          DOCUMENT NAME   MAKE MODEL  MODEL YEAR  \
0      23V173  RCRIT-23V173-6991.pdf  VOLVO   VHD        2024
1      23V173  RCRIT-23V173-4613.pdf  VOLVO   VHD        2024
2      23V173  RCRIT-23V173-3354.pdf  VOLVO   VHD        2024
3      23V173   RCMN-23V173-3463.pdf  VOLVO   VHD        2024
4      23V173  RCRIT-23V173-7160.pdf  VOLVO   VHD        2024
...       ...                    ...    ...   ...         ...
6590   24V962   RCMN-24V962-3806.pdf    KIA   EV9        2024
6591   24V962  RCRIT-24V962-7747.pdf    KIA   EV9        2024
6592   24V962  RCONL-24V962-1772.pdf    KIA   EV9        2024
6593   24V962   RCMN-24V962-3299.pdf    KIA   EV9        2024
6594   24V962   RCMN-24V962-3393.pdf    KIA   EV9        2024

                                                SUMMARY
0     On certain trucks, the hub covers on the drive...
1     On certain trucks, the hub covers on the drive...
2     Volvo has determined that some hub covers, lac...
3     On certain trucks, the hub covers on the drive...
4     Volvo has determined that some hub covers, lac...
...                                                 ...
6590  The Q&A contains questions and answers regardi...
6591  The Technical Service Bulletin (TSB) lists spe...
6592  Owner Letter notifies the customer of the safe...
6593  The Dealer Parts & Service Manager letter is t...
6594  The Dealer Principal letter is to notify the d...

[6595 rows x 6 columns]>

,NHTSA ID,DOCUMENT NAME,MAKE,MODEL,MODEL YEAR,SUMMARY
0,23V173,RCRIT-23V173-6991.pdf,VOLVO,VHD,2024,"On certain trucks, the hub covers on the drive..."
1,23V173,RCRIT-23V173-4613.pdf,VOLVO,VHD,2024,"On certain trucks, the hub covers on the drive..."
2,23V173,RCRIT-23V173-3354.pdf,VOLVO,VHD,2024,"Volvo has determined that some hub covers, lac..."
3,23V173,RCMN-23V173-3463.pdf,VOLVO,VHD,2024,"On certain trucks, the hub covers on the drive..."
4,23V173,RCRIT-23V173-7160.pdf,VOLVO,VHD,2024,"Volvo has determined that some hub covers, lac..."
5,23V173,RCONL-23V173-9318.pdf,VOLVO,VHD,2024,"Volvo has determined that some hub covers, lac..."
6,23V173,RCONL-23V173-9318.pdf,VOLVO,VNL,2024,"Volvo has determined that some hub covers, lac..."
7,23V173,RCMN-23V173-3463.pdf,VOLVO,VNL,2024,"On certain trucks, the hub covers on the drive..."
8,23V173,RCRIT-23V173-7160.pdf,VOLVO,VNL,2024,"Volvo has determined that some hub covers, lac..."
9,23V173,RCRIT-23V173-6991.pdf,VOLVO,VNL,2024,"On certain trucks, the hub covers on the drive..."
10,23V173,RCRIT-23V173-4613.pdf,VOLVO,VNL,2024,"On certain trucks, the hub covers on the drive..."
11,23V173,RCRIT-23V173-3354.pdf,VOLVO,VNL,2024,"Volvo has determined that some hub covers, lac..."
12,23V173,RCRIT-23V173-4613.pdf,VOLVO,VNR,2024,"On certain trucks, the hub covers on the drive..."
13,23V173,RCONL-23V173-9318.pdf,VOLVO,VNR,2024,"Volvo has determined that some hub covers, lac..."
14,23V173,RCMN-23V173-3463.pdf,VOLVO,VNR,2024,"On certain trucks, the hub covers on the drive..."
15,23V173,RCRIT-23V173-7160.pdf,VOLVO,VNR,2024,"Volvo has determined that some hub covers, lac..."
16,23V173,RCRIT-23V173-6991.pdf,VOLVO,VNR,2024,"On certain trucks, the hub covers on the drive..."
17,23V173,RCRIT-23V173-3354.pdf,VOLVO,VNR,2024,"Volvo has determined that some hub covers, lac..."
18,23V280,RCRIT-23V280-5344.pdf,VOLVO,VNR,2024,Coolant Lines in battery pack may not be prope...
19,23V280,RCRIT-23V280-5658.pdf,VOLVO,VNR,2024,Coolant Lines in battery pack may not be prope...