In [124]:
import pandas 
import matplotlib
import seaborn

import pandas as pd
df = pd.read_csv("vehicles_dataset.csv")

#import pandas as pd
#df = pd.read_csv("RCL_FROM_2020_2024.csv")

In [125]:
pd.set_option('display.max_columns', None)

#Read Car List dataframe and show maximum columns
 
df_CarList = pd.read_csv("vehicles_dataset.csv")
df_CarList.info(max_cols=20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1002 entries, 0 to 1001
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            1002 non-null   object
 1   description     946 non-null    object
 2   make            1002 non-null   object
 3   model           1002 non-null   object
 4   type            1002 non-null   object
 5   year            1002 non-null   int64
 6   price           979 non-null    float64
 7   engine          1000 non-null   object
 8   cylinders       897 non-null    float64
 9   fuel            995 non-null    object
 10  mileage         968 non-null    float64
 11  transmission    1000 non-null   object
 12  trim            1001 non-null   object
 13  body            999 non-null    object
 14  doors           995 non-null    float64
 15  exterior_color  997 non-null    object
 16  interior_color  964 non-null    object
 17  drivetrain      1002 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 141.0+ KB

In [126]:
df_CarList = df_CarList[df_CarList['year'] == 2024]
df.reset_index(drop=True, inplace=True)

Find Missing values

In [127]:

df_CarList[df_CarList.isnull().any(axis=1)]

,name,description,make,model,type,year,price,engine,cylinders,fuel,mileage,transmission,trim,body,doors,exterior_color,interior_color,drivetrain
2,2024 GMC Yukon XL Denali,NaN,GMC,Yukon XL,New,2024,96410.0,"6.2L V-8 gasoline direct injection, variable v...",8.0,Gasoline,0.0,Automatic,Denali,SUV,4.0,Summit White,Teak/Light Shale,Four-wheel Drive
8,2024 Hyundai Tucson Hybrid Limited,NaN,Hyundai,Tucson Hybrid,New,2024,42230.0,16V GDI DOHC Turbo Hybrid,4.0,Hybrid,5.0,6-Speed Automatic,Limited,SUV,4.0,White Pearl,Black,All-wheel Drive
14,2024 Chevrolet Blazer EV 2LT,\n \n Sterling Gray Metallic 2024 ...,Chevrolet,Blazer EV,New,2024,51695.0,c,NaN,Electric,4.0,1-Speed Automatic,2LT,SUV,4.0,Sterling Gray Metallic,Black,All-wheel Drive
23,2024 GMC Terrain Denali,NaN,GMC,Terrain,New,2024,44120.0,"4 gasoline direct injection, DOHC, variable va...",4.0,Gasoline,0.0,Automatic,Denali,SUV,4.0,Ebony,Jet Blk,All-wheel Drive
27,2024 Chrysler Pacifica Touring-L,\n \n $750 off MSRP! 2024 Chrysler...,Chrysler,Pacifica,New,2024,48705.0,24V MPFI DOHC,6.0,Gasoline,NaN,9-Speed Automatic,Touring-L,Passenger Van,4.0,Diamond Black,Black,All-wheel Drive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
977,2024 Kia Sportage SX-Prestige,NaN,Kia,Sportage,New,2024,35195.0,16V PDI DOHC,4.0,Gasoline,10.0,8-Speed Automatic,SX-Prestige,SUV,4.0,Ebony Black,Black,Front-wheel Drive
978,2024 Kia EV6 Wind,Aurora Black Pearl 2024 Kia EV6 Wind AWD 1-Spe...,Kia,EV6,New,2024,43439.0,c,NaN,Electric,14.0,Automatic,Wind,SUV,4.0,Aurora Black Pearl,Black,All-wheel Drive
980,2024 Kia Forte LXS,\n \n 2024 Kia Forte Steel Gray LX...,Kia,Forte,New,2024,21070.0,16V MPFI DOHC,4.0,Gasoline,NaN,Automatic CVT,LXS,Sedan,4.0,Steel Gray,Black,Front-wheel Drive
985,2024 Hyundai Tucson Hybrid SEL Convenience,NaN,Hyundai,Tucson Hybrid,New,2024,37220.0,16V GDI DOHC Turbo Hybrid,4.0,Hybrid,5.0,6-Speed Automatic,SEL Convenience,SUV,4.0,Deep Sea,Gray,All-wheel Drive
987,2024 Hyundai Tucson Hybrid SEL Convenience,NaN,Hyundai,Tucson Hybrid,New,2024,37309.0,16V GDI DOHC Turbo Hybrid,4.0,Hybrid,5.0,6-Speed Automatic,SEL Convenience,SUV,4.0,Amazon Gray,Black,All-wheel Drive

We have 252 rows of missing values. Lets clean this up by removing uneccessary columns and remove rows with NaN values

In [128]:

#df_CarList.to_csv('vehicles_dataset.csv', index=False) #Saves cleaned data to a new file

In [129]:
df_CarList.drop(columns=["description","fuel","type","engine","interior_color","exterior_color","mileage","doors"], inplace=True)

In [130]:
df_CarList.drop_duplicates()

,name,make,model,year,price,cylinders,transmission,trim,body,drivetrain
0,2024 Jeep Wagoneer Series II,Jeep,Wagoneer,2024,74600.0,6.0,8-Speed Automatic,Series II,SUV,Four-wheel Drive
1,2024 Jeep Grand Cherokee Laredo,Jeep,Grand Cherokee,2024,50170.0,6.0,8-Speed Automatic,Laredo,SUV,Four-wheel Drive
2,2024 GMC Yukon XL Denali,GMC,Yukon XL,2024,96410.0,8.0,Automatic,Denali,SUV,Four-wheel Drive
4,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive
5,2024 Nissan Murano Platinum,Nissan,Murano,2024,46000.0,6.0,Automatic CVT,Platinum,SUV,All-wheel Drive
...,...,...,...,...,...,...,...,...,...,...
996,2024 RAM 2500 Tradesman,RAM,2500,2024,69315.0,6.0,Automatic,Tradesman,Pickup Truck,Four-wheel Drive
997,2024 Mercedes-Benz Sprinter 2500 Standard Roof,Mercedes-Benz,Sprinter 2500,2024,59037.0,4.0,9-Speed Automatic,Standard Roof,Cargo Van,Rear-wheel Drive
999,2024 Jeep Wagoneer Base,Jeep,Wagoneer,2024,69085.0,6.0,8-Speed Automatic,Base,SUV,Four-wheel Drive
1000,2024 Nissan Murano SV Intelligent AWD,Nissan,Murano,2024,43495.0,6.0,Automatic,SV Intelligent AWD,SUV,All-wheel Drive
1001,2024 Chevrolet Silverado 2500 WT,Chevrolet,Silverado 2500,2024,48995.0,8.0,Automatic,WT,Pickup Truck,Rear-wheel Drive

In [131]:
#df.isnull().sum()
df_CarList.isnull().sum()

name             0
make             0
model            0
year             0
price           21
cylinders       95
transmission     2
trim             0
body             3
drivetrain       0
dtype: int64

In [132]:
#Find missing values again which resulted in 130 this time
df_CarList[df_CarList.isnull().any(axis=1)]

,name,make,model,year,price,cylinders,transmission,trim,body,drivetrain
14,2024 Chevrolet Blazer EV 2LT,Chevrolet,Blazer EV,2024,51695.0,NaN,1-Speed Automatic,2LT,SUV,All-wheel Drive
28,2024 Chevrolet Blazer EV 2LT,Chevrolet,Blazer EV,2024,52190.0,NaN,1-Speed Automatic,2LT,SUV,All-wheel Drive
33,2024 Kia EV6 GT,Kia,EV6,2024,49820.0,NaN,Automatic,GT,SUV,All-wheel Drive
35,2024 Ford Mustang Mach-E Premium,Ford,Mustang Mach-E,2024,47790.0,NaN,1-Speed Automatic,Premium,SUV,All-wheel Drive
49,2024 Hyundai IONIQ 5 SE Standard Range,Hyundai,IONIQ 5,2024,44195.0,NaN,1-Speed Automatic,SE Standard Range,SUV,Rear-wheel Drive
...,...,...,...,...,...,...,...,...,...,...
940,2024 Ford Transit-350 148 WB Medium Roof Cargo,Ford,Transit-350,2024,52530.0,6.0,NaN,148 WB Medium Roof Cargo,Cargo Van,Rear-wheel Drive
941,2024 Hyundai IONIQ 5 SE,Hyundai,IONIQ 5,2024,38201.0,NaN,Automatic,SE,SUV,Rear-wheel Drive
943,2024 Ford Edge ST-Line,Ford,Edge,2024,NaN,4.0,8-Speed Automatic,ST-Line,SUV,All-wheel Drive
944,2024 Kia EV6 Wind,Kia,EV6,2024,41528.0,NaN,Automatic,Wind,SUV,All-wheel Drive
978,2024 Kia EV6 Wind,Kia,EV6,2024,43439.0,NaN,Automatic,Wind,SUV,All-wheel Drive

In [140]:
#Replacing NaN vaules in cyclinder with 'Eletric' for the Electric Vehicles
df_CarList['cylinders']= df_CarList['cylinders'].fillna("Electric")
#Fixing missing values in transmiddion column
df_CarList['transmission']=df_CarList['transmission'].fillna("Automatic")

#Adding SUV to NaNs in the column 'body'
df_CarList['body']=df_CarList['body'].fillna("SUV")

#Recheck missing values
df_CarList[df_CarList.isnull().any(axis=1)]

,name,make,model,year,price,cylinders,transmission,trim,body,drivetrain
142,2024 Mercedes-Benz EQS 450 Base 4MATIC,Mercedes-Benz,EQS 450,2024,NaN,Electric,Automatic,Base 4MATIC,Sedan,All-wheel Drive
248,2024 Dodge Durango Pursuit,Dodge,Durango,2024,NaN,8.0,8-Speed Automatic,Pursuit,SUV,All-wheel Drive
328,2024 Mercedes-Benz EQS 450 Base 4MATIC,Mercedes-Benz,EQS 450,2024,NaN,Electric,Automatic,Base 4MATIC,Sedan,All-wheel Drive
372,2024 Mercedes-Benz EQS 450 Base 4MATIC,Mercedes-Benz,EQS 450,2024,NaN,Electric,Automatic,Base 4MATIC,Sedan,All-wheel Drive
417,2024 RAM 3500 Tradesman,RAM,3500,2024,NaN,8.0,8-Speed Automatic,Tradesman,Pickup Truck,Four-wheel Drive
443,2024 Jeep Compass Limited,Jeep,Compass,2024,NaN,4.0,8-Speed Automatic,Limited,SUV,Four-wheel Drive
500,2024 Ford Edge SE,Ford,Edge,2024,NaN,4.0,8-Speed Automatic,SE,SUV,All-wheel Drive
506,2024 Dodge Durango Pursuit,Dodge,Durango,2024,NaN,6.0,8-Speed Automatic,Pursuit,SUV,All-wheel Drive
536,2024 Dodge Hornet GT,Dodge,Hornet,2024,NaN,4.0,9-Speed Automatic,GT,SUV,All-wheel Drive
541,2024 RAM 3500 Big Horn,RAM,3500,2024,NaN,6.0,6-Speed Automatic,Big Horn,Pickup Truck,Four-wheel Drive
627,2024 Dodge Hornet R/T,Dodge,Hornet,2024,NaN,4.0,6-Speed Automatic,R/T,SUV,All-wheel Drive
678,2024 Hyundai Santa Cruz 2.5T Limited,Hyundai,Santa Cruz,2024,NaN,4.0,8-Speed Automatic with Auto-Shift,2.5T Limited,Pickup Truck,All-wheel Drive
683,2024 Mercedes-Benz GLE 350 Base 4MATIC,Mercedes-Benz,GLE 350,2024,NaN,4.0,9-Speed Automatic,Base 4MATIC,SUV,All-wheel Drive
704,2024 Ford Edge ST-Line,Ford,Edge,2024,NaN,4.0,8-Speed Automatic,ST-Line,SUV,All-wheel Drive
779,2024 Ford Edge SE,Ford,Edge,2024,NaN,4.0,8-Speed Automatic,SE,SUV,All-wheel Drive
809,2024 Jeep Grand Cherokee Laredo,Jeep,Grand Cherokee,2024,NaN,6.0,8-Speed Automatic,Laredo,SUV,Four-wheel Drive
811,2024 BMW 530 i,BMW,530,2024,NaN,4.0,8-Speed Automatic,i,Sedan,Rear-wheel Drive
859,2024 Dodge Hornet R/T,Dodge,Hornet,2024,NaN,4.0,6-Speed Automatic,R/T,SUV,All-wheel Drive
876,2024 Ford Edge SE,Ford,Edge,2024,NaN,4.0,8-Speed Automatic,SE,SUV,All-wheel Drive
937,2024 Dodge Hornet GT,Dodge,Hornet,2024,NaN,4.0,9-Speed Automatic,GT,SUV,All-wheel Drive
943,2024 Ford Edge ST-Line,Ford,Edge,2024,NaN,4.0,8-Speed Automatic,ST-Line,SUV,All-wheel Drive

In [141]:
df_CarList.isnull().sum()

name             0
make             0
model            0
year             0
price           21
cylinders        0
transmission     0
trim             0
body             0
drivetrain       0
dtype: int64